Import Frames from another FrameResource QOL
Greavesy1899/MafiaToolkit pull request #108
Opened 2024-10-11 12:34 UTC by Kozmeker

Added importing frames from another FrameResource. In order to be able to do this, SceneData has been rewritten to not be static, this may cause issues or bugs, some of them I managed to find, but if there are any, they should be reported to be taken care of.
Maybe this should be noted somewhere, just in case.

2024-10-25 08:08 UTC, Greavesy1899 requested changes

2024-10-26 04:20 UTC, Kozmeker commented on Mafia2Libs/Rendering/Graphics/TextureClass.cs
> +        public static SceneData SceneData = new SceneData();
Since it uses scenepath I changed it only for string

2024-10-26 04:28 UTC, Kozmeker commented on Mafia2Libs/Rendering/Graphics/GraphicsClass.cs
> +        public SceneData SceneData = new SceneData();
PickOutParams uses it one time in certain situation

2024-10-26 04:39 UTC, Kozmeker commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +            MemoryStream mainMemoryStream = new MemoryStream();
I am gonna need time to think this through

2024-10-26 04:39 UTC, Kozmeker commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +            if (memoryStream == null)
same as WriteToStream

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Graphics/GraphicsClass.cs
> +        public SceneData SceneData = new SceneData();
If its just to log an error i'd say get rid of it as well as this additional memeber.

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Graphics/GraphicsClass.cs
> +        public SceneData SceneData = new SceneData();
This I assume: https://github.com/Greavesy1899/MafiaToolkit/blob/46b49810d2a3030f95da33bb403951adac64585b/Mafia2Libs/Rendering/Graphics/GraphicsClass.cs#L207

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Graphics/RenderTypes/RenderModel.cs
> +using Mafia2Tool;
Can we remove?

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Graphics/TextureClass.cs
> +        public static string ScenePath;
When is this assigned?

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Factories/RenderableFactory.cs
> +        public static RenderModel BuildRenderModelFromFrame(FrameObjectSingleMesh Mesh,SceneData sceneData)
You could get rid of SceneData parameter, as we created new functions to fetch buffer from FrameObjectSingleMesh.

See line 46 and line 47.

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Rendering/Factories/RenderableFactory.cs
> +        public static RenderModel BuildRenderModelFromFrame(FrameObjectSingleMesh Mesh,SceneData sceneData)
Then you can remove SceneData from this class entirely.

2024-10-27 19:19 UTC, Greavesy1899 commented on Mafia2Libs/Forms/MapEditor.cs
> +        private bool CheckForMeshObjects(TreeNode node)//checking for at least one SingleMesh
Whats this used by? Could be within FrameResource and iterate through their own internal list

2024-10-29 00:48 UTC, Kozmeker commented on Mafia2Libs/Rendering/Factories/RenderableFactory.cs
> +        public static RenderModel BuildRenderModelFromFrame(FrameObjectSingleMesh Mesh,SceneData sceneData)
I don't think so, because geometry and material is givem from SD, so we either make new functions for that aswell or leave it like that for now, also its needed for Itemdescs

2024-10-29 00:56 UTC, Kozmeker commented on Mafia2Libs/Rendering/Factories/RenderableFactory.cs
> +        public static RenderModel BuildRenderModelFromFrame(FrameObjectSingleMesh Mesh,SceneData sceneData)
since new functions are within objects(IB,VB) owned by SD,

2024-10-29 02:08 UTC, Kozmeker commented on Mafia2Libs/Rendering/Graphics/TextureClass.cs
> +        public static string ScenePath;
map editor after init

2024-10-29 19:55 UTC, Greavesy1899 commented on Mafia2Libs/Controls/ListWindow.cs
> +        public void PopulateForm(ParentInfo.ParentType ParentType,SceneData sceneData)
As discussed in discord

2024-10-29 19:55 UTC, Greavesy1899 commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                        OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
We don't need to access OwningResource here, just use `mesh` to get buffers

2024-10-29 19:55 UTC, Greavesy1899 commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                        OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
We don't need to access OwningResource here, just use mesh to get buffers

2024-10-29 19:55 UTC, Greavesy1899 commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                            OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
Same with this, use `mesh`

2024-10-29 19:55 UTC, Greavesy1899 commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FrameResource.cs
> +        public SceneData SceneData = new SceneData();
Can we set this to `= null`?

2024-10-29 20:37 UTC, Kozmeker commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                        OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
needs to be rewritten later with its duplicates

2024-10-29 20:38 UTC, Kozmeker commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                        OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
needs to be rewritten later with its duplicates, with 211-212

2024-10-29 20:47 UTC, Kozmeker commented on Mafia2Libs/ResourceTypes/FileTypes/FrameResource/FramePack.cs
> +                            OwningResource.SceneData.IndexBufferPool.GetBuffer(lod.IndexBufferRef.Hash).WriteToFile(stream, false);
as above

2024-10-30 14:30 UTC, merged